#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=Trainmetatitan
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=10:00:00
#SBATCH --mem=32000M
#SBATCH --output=hindipretrainjob.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/atcs_proj/udify-metalearning
python train.py --config config/ud/hi/udify_bert_finetune_hindi.json --name bert_finetune_hindi
